baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vitae"
theme = "hugo-vitae"
paginate = 5

copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "hugo-vitae"

[taxonomies]
	tag = "tags"
	series = "series"

[params]
	subtitle = "[Vitae](https://github.com/dataCobra/hugo-vitae) is a blog theme for Hugo that focuses on your content."

	# Optional 80x80 avatar image.
	avatar = "/img/vitae.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/dataCobra/hugo-vitae"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
